<?php
namespace Krymen\SensorsBundle\Entity;

/**
 * SensorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
interface SensorRepositoryInterface
{
    public function find($id);

    public function findAll();

    public function add(Sensor $sensor);

    public function remove(Sensor $sensor);
}
