parameters:
#    krymen_sensors.example.class: Krymen\SensorsBundle\Example

services:
#    krymen_sensors.example:
#        class: %krymen_sensors.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
